# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queue.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bqueue.proto\x12\x05queue\"\'\n\x11StartQueueRequest\x12\x12\n\nqueue_name\x18\x01 \x01(\t\"$\n\x12StartQueueResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\")\n\x13\x43onsumeQueueRequest\x12\x12\n\nqueue_name\x18\x01 \x01(\t\"\'\n\x14\x43onsumeQueueResponse\x12\x0f\n\x07message\x18\x01 \x01(\x0c\"8\n\x11\x41\x64\x64MessageRequest\x12\x12\n\nqueue_name\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\x0c\"$\n\x12\x41\x64\x64MessageResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xdf\x01\n\x0cQueueService\x12\x41\n\nStartQueue\x12\x18.queue.StartQueueRequest\x1a\x19.queue.StartQueueResponse\x12I\n\x0c\x43onsumeQueue\x12\x1a.queue.ConsumeQueueRequest\x1a\x1b.queue.ConsumeQueueResponse0\x01\x12\x41\n\nAddMessage\x12\x18.queue.AddMessageRequest\x1a\x19.queue.AddMessageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'queue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTQUEUEREQUEST']._serialized_start=22
  _globals['_STARTQUEUEREQUEST']._serialized_end=61
  _globals['_STARTQUEUERESPONSE']._serialized_start=63
  _globals['_STARTQUEUERESPONSE']._serialized_end=99
  _globals['_CONSUMEQUEUEREQUEST']._serialized_start=101
  _globals['_CONSUMEQUEUEREQUEST']._serialized_end=142
  _globals['_CONSUMEQUEUERESPONSE']._serialized_start=144
  _globals['_CONSUMEQUEUERESPONSE']._serialized_end=183
  _globals['_ADDMESSAGEREQUEST']._serialized_start=185
  _globals['_ADDMESSAGEREQUEST']._serialized_end=241
  _globals['_ADDMESSAGERESPONSE']._serialized_start=243
  _globals['_ADDMESSAGERESPONSE']._serialized_end=279
  _globals['_QUEUESERVICE']._serialized_start=282
  _globals['_QUEUESERVICE']._serialized_end=505
# @@protoc_insertion_point(module_scope)
